# Generated by Django 4.1.3 on 2022-11-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_rename_topic_blog_blogidea'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsection',
            name='wordCount',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
